site_name: pchtps's blogue
site_url: https://pchtsp.github.io/blogue2.0/
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  # Add more pages here, e.g.:
  # - About: about.md
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
      separator: "_"
